name: Deploy Static Website with CloudFormation

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::932877337538:role/github-s3-deploy-role
          aws-region: sa-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: AfricanRestaurantWebsiteStack
          template: template.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "BucketName=my-african-restaurant-site-932877337538"

      - name: Apply Public Bucket Policy
        run: |
          aws s3api put-bucket-policy \
            --bucket my-african-restaurant-site-932877337538 \
            --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "PublicReadGetObject",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::my-african-restaurant-site-932877337538/*"
                }
              ]
            }'

      - name: Sync Site Assets to S3
        run: |
          aws s3 sync . s3://my-african-restaurant-site-932877337538 \
            --delete \
            --exclude ".git*" \
            --exclude "template.yaml" \
            --exclude ".github*" \
            --exclude "*.md" \
            --exclude "*.json"

      - name: Print Live Website URL
        run: |
          echo "🚀 Deployed Successfully via CloudFormation!"
          echo "Your live website URL is:"
          aws cloudformation describe-stacks \
            --stack-name AfricanRestaurantWebsiteStack \
            --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" \
            --output text
